spring:
  datasource:
    url: jdbc:postgresql://dpg-cpj5bk6ct0pc73848620-a.frankfurt-postgres.render.com:5432/skateshop
    username: maropce
    password: YMNnqin9hCjvPHUV850500QVAxjL6S3g
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  h2:
    console:
      enabled: false



#spring:
#  datasource:
#    url: jdbc:h2:file:./data/demo
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true
#    database: h2
#  h2:
#    console:
#      enabled: true

